---
- name: Install nginx
  hosts: all
  become: true
  tasks:
  - name: Update all packages
    dnf:
      name: "*"
      state: latest
      update_cache: yes

  - name: Install nginx
    dnf:
      name: nginx
      state: latest

  - name: Enable nginx
    systemd:
      name: nginx
      state: restarted
      enabled: yes

  - name: install python3-firewalld
    dnf:
      name: python3-firewalld
      state: present

  - name: firewalld enable http(s)
    firewalld:
      service:
        - http
        - https
      state: enabled
      permanent: yes
      immediate: yes